version: '3'
services:
  db:
    image: mongo:3.4
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 80:80